Feat: Search for barcode
InventoryAssistant/InventoryAssistantAPI pull request #4
Opened 2024-04-22 08:19 UTC by MathiasDuus

2024-04-22 11:22 UTC, MathiasDuus commented
![](https://github.trello.services/images/mini-trello-icon.png) [API - barcode lookup](https://trello.com/c/j4YZUHpx/30-api-barcode-lookup)

2024-04-22 12:07 UTC, Setanna requested changes

2024-04-22 12:07 UTC, Setanna commented on app/Http/Controllers/ProductController.php
> +            }
The function should properly check our database first for any hits

2024-04-22 12:11 UTC, MathiasDuus commented on app/Http/Controllers/ProductController.php
> +            }
I have done the thing

2024-04-23 06:31 UTC, Setanna approved these changes

2024-04-23 06:32 UTC, merged